### ISSUE TITLE
Precision issue

### ISSUE THREAD

**Issue by adrigzr** [royNiladri/js-big-decimal#121]
**Describe the bug**
Invalid result using divide.

```javascript
new bigDecimal("29.45").divide(new bigDecimal("646")).multiply(new bigDecimal("646")).getValue() === "29.45"; // 29.45000304
new bigDecimal("29.45").divide(new bigDecimal("646"), 16).multiply(new bigDecimal("646")).getValue() === "29.45"; // 29.4499999999999696
new bigDecimal("29.45").divide(new bigDecimal("646"), 32).multiply(new bigDecimal("646")).getValue() === "29.45"; // 29.44999999999999999999999999999696
```

**To Reproduce**
```javascript
const { default: bigDecimal } = require("js-big-decimal");

console.log(new bigDecimal("29.45").divide(new bigDecimal("646")).multiply(new bigDecimal("646")).getValue()); // 29.45000304
console.log(new bigDecimal("29.45").divide(new bigDecimal("646"), 16).multiply(new bigDecimal("646")).getValue()); // 29.4499999999999696
console.log(new bigDecimal("29.45").divide(new bigDecimal("646"), 32).multiply(new bigDecimal("646")).getValue()); // 29.44999999999999999999999999999696
```

**Expected behavior**
```javascript
new bigDecimal("29.45").divide(new bigDecimal("646")).multiply(new bigDecimal("646")).getValue() === "29.45"; // 29.45
```

**Additional context**
Thanks for this great lib 😄

**Comment by royNiladri** [comment]
Hi, this is kind of expected.
When the precision is not set, it defaults to 8. When it is set, it takes that value. Looks like dividing by 646 does not result in a finite number after decimals, when you perform the divide, some rounding off happens. When you multiply back, it results in a minor variation. To overcome this, you can use a higher precision in divide, and round off in multiply by required precision, or do multiply and then divide. Let me know if that sounds reasonable.

**Comment by adrigzr** [comment]
Hi @royNiladri, yes, that makes sense. Thanks for your response 😄
