### ISSUE TITLE
Function compareTo fails when comparing 0 and -0

### ISSUE THREAD

**Issue by joaoccruz** [royNiladri/js-big-decimal#122]
**Describe the bug**
Attempting to run bigDecimal.compareTo("-0", "0") returns -1, assuming -0 is lower than 0, when they are mathematically equal. This is always true, on the cases I tested, even when applying exponentials to either of the two operands.

Package version: 2.0.4

**To Reproduce**
bigDecimal.compareTo("-0", "0") === -1 
> true

**Expected behavior**
One would expect that compareTo would return 0 (equal) for the operations  bigDecimal.compareTo("-0", "0") and bigDecimal.compareTo("0", "-0").

**Comment by royNiladri** [comment]
Fixed in v2.0.7
