### ISSUE TITLE
Uncaught TypeError: bigDecimal is not a constructor

### ISSUE THREAD

**Issue by wildtang** [royNiladri/js-big-decimal#138]
**Describe the bug**
When use in html file with <script> tag, new bigDecimal('0.3') show error: Uncaught TypeError: bigDecimal is not a constructor

**To Reproduce**
I wrote a html file, and double click it to open using browser Edge (version is v128),
there is an error in the browser console, see the comment marked with ★ in below html/js code.

```
<!DOCTYPE html>

<head>
    <script src="node_modules/js-big-decimal/dist/web/js-big-decimal.min.js"></script>
    <script src="node_modules/vue/dist/vue.js"></script>
    
</head>

<body>
    <div id="app-view-area">
        <input v-model="number1">
        {{operator}}
        <input v-model="number2">
        =
        {{ sum }}
        <button @click="newQuestion">Random Question</button>
    </div>
    
      <script>
        // ★In browser Edge(v128) console, the line below has error: 
        // ↓ Uncaught TypeError: bigDecimal is not a constructor
        var someVal = new bigDecimal('0.3')

        var app = new Vue({
          el: '#app-view-area',
          
          data: {
            number1: "0.1",
            number2: "0.2",
            operator: "+",
          },
          computed: {
            sum: {
              get: function () {
                // Use Big Decimal to prevent the problem like 0.1+0.2 => 0.30000000000000004
                // https://github.com/royNiladri/js-big-decimal
               var value1 = new bigDecimal(this.number1);
               var value2 = new bigDecimal(this.number2);
                if (this.operator === '-') {
                  return bigDecimal.subtract(value1, value2).toFixed(1).getValue();
                } else {
                  return bigDecimal.add(value1, value2).toFixed(1).getValue();
                }
              }
            }
          },
          methods: {
            newQuestion: function () {
              // generate two random numbers between [-100, 100]
              this.number1 = (Math.random() * 200 - 100).toFixed(1);
              this.number2 = (Math.random() * 200 - 100).toFixed(1);
              this.operator = Math.random() < 0.5 ? '+' : '-';
            },
          }
        })
    </script>
</body>

</html>

```
![图片](https://github.com/user-attachments/assets/16b2fc09-0979-4697-bc94-2d6c7c80428a)
![图片](https://github.com/user-attachments/assets/a2fabd2d-cda9-4ef6-a336-844eb2976949)

**Expected behavior**
No this error: Uncaught TypeError: bigDecimal is not a constructor

**Additional context**

Content of package.json is:

```
{
  "dependencies": {
    "js-big-decimal": "^2.1.0",
    "vue": "^2.7.16"
  }
}

```

**Comment by royNiladri** [comment]
This is an issue with default export. Will need to investigate and fix. In the meantime, you can use something like this, by accessing default.

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/585e58ff-3726-4d88-8d27-485838e98cc4">

**Comment by wildtang** [comment]
@royNiladri 
Thanks, var someVal = new bigDecimal.default('0.3') works.

But bigDecimal.add location still has error, see ★ comment in code below.
And if I change bigDecimal.add to bigDecimal.default.add, another error will shows "[Vue warn]: Error in render: "Error: Parameter is not a number: [object Object]""

```
<!DOCTYPE html>

<head>
    <script src="../node_modules/js-big-decimal/dist/web/js-big-decimal.min.js"></script>
    <script src="../node_modules/vue/dist/vue.js"></script>
    
</head>

<body>
    <div id="app-view-area">
        <input v-model="number1">
        {{operator}}
        <input v-model="number2">
        =
        {{ sum }}
        <button @click="newQuestion">Random Question</button>
    </div>
    
      <script>
        // ↓ Here passed by add .default
        var someVal = new bigDecimal.default('0.3')

        // ★ browser Edge console error here:
        // [Vue warn]: Error in render: "TypeError: bigDecimal.add is not a function"
        var app = new Vue({
          el: '#app-view-area',
          
          data: {
            number1: "0.1",
            number2: "0.2",
            operator: "+",
          },
          computed: {
            sum: {
              get: function () {
                // Use Big Decimal to prevent the problem like 0.1+0.2 => 0.30000000000000004
                // https://github.com/royNiladri/js-big-decimal
               var value1 = new bigDecimal.default(this.number1);
               var value2 = new bigDecimal.default(this.number2);
                if (this.operator === '-') {
                  return bigDecimal.subtract(value1, value2).toFixed(1).getValue();
                } else {
                  return bigDecimal.add(value1, value2).toFixed(1).getValue();
                }
              }
            }
          },
          methods: {
            newQuestion: function () {
              // generate two random numbers between [-100, 100]
              this.number1 = (Math.random() * 200 - 100).toFixed(1);
              this.number2 = (Math.random() * 200 - 100).toFixed(1);
              this.operator = Math.random() < 0.5 ? '+' : '-';
            },
          }
        })
    </script>
</body>

</html>
```

![图片](https://github.com/user-attachments/assets/a9b85c82-886b-4087-9fec-3ace5cd60f54)
![图片](https://github.com/user-attachments/assets/9e63a7b1-4073-4c09-ba55-4c9ba7a6d430)

**Comment by royNiladri** [comment]
The whole module has now got wrapped in default. You can overwrite
bigDecimal = bigDecimal.default. and then use it as in the readme.

**Comment by wildtang** [comment]
I tested bigDecimal = bigDecimal.default,but not works with Vue 2.😉

I used a package named decimal.js(v10.4.3) resolved my problem.
Thanks for your replies, When the default export problem resolved, I will test js-big-decimal again💖

**Comment by vgrunner4v** [comment]
Hey, is there any update on this issue? i'm facing it too with v2+ (not happened on v1.4.1 for example)

**Comment by Jsoto22** [comment]
@vgrunner4v @wildtang I'll look into this soon if I can. May have to modify the config and do some external testing specifically for Vue 2.

**Comment by royNiladri** [comment]
Hi @wildtang @vgrunner4v, I made some changes and tried it out locally. Seems to be working as expected. Please try out the latest version 2.2.0 and let know.
Another note, @wildtang the add usage is not correct. We suppot one big decimal adding another or 2 numbers/string being added with bigDecimal.add. Correct usage would look like:
```
var value1 = new bigDecimal(this.number1);
var value2 = new bigDecimal(this.number2);
if (this.operator === '-') {
   return value1.subtract(value2).round(1).getValue();
} else {
    return value1.add(value2).round(1).getValue();
}
```

**Comment by wildtang** [comment]
> Hi @wildtang @vgrunner4v, I made some changes and tried it out locally. Seems to be working as expected. Please try out the latest version 2.2.0 and let know. Another note, @wildtang the add usage is not correct. We suppot one big decimal adding another or 2 numbers/string being added with bigDecimal.add. Correct usage would look like:
> 
> ```
> var value1 = new bigDecimal(this.number1);
> var value2 = new bigDecimal(this.number2);
> if (this.operator === '-') {
>    return value1.subtract(value2).round(1).getValue();
> } else {
>     return value1.add(value2).round(1).getValue();
> }
> ```

@royNiladri @Jsoto22 
It works! What are nice men you are!
