### ISSUE TITLE
setValue is not a function, however ...

### ISSUE THREAD

**Issue by FireMuse** [royNiladri/js-big-decimal#140]
In the example in the documentation:

`var n = new bigDecimal('123');
n.setvalue('567');`

setvalue is not a function.  However this works:

`var n = new bigDecimal('123');
n.value = 567;`

This is possibly just out of date documentation.

**Comment by Jsoto22** [comment]
@FireMuse there's a type in the documentation. I'll fix soon.

**Comment by royNiladri** [comment]
Thanks @Jsoto22. I have updated in the master branch. Not creating a release for this. This change will go as part of the next release.
