### ISSUE TITLE
can't find module RoundingModes

### ISSUE THREAD

**Issue by shiyafei** [royNiladri/js-big-decimal#17]
`import bigDecimal from 'js-big-decimal'

export class RunUtils {

  public static scaleFloat(value: number, scale: number) {
    let strValue = value.toString()
    let decimalValue = new bigDecimal(strValue)
    return decimalValue.round(scale, bigDecimal.RoundingModes.HALF_UP).getValue()
  }
}`

then error: can't find module RoundingModes

**Comment by royNiladri** [comment]
Fixed in v1.2.1
Please check and let us know.
