### ISSUE TITLE
2.00 / 0.5 = 40.00000000

### ISSUE THREAD

**Issue by valerashylin** [royNiladri/js-big-decimal#18]
Inconsistency in treating decimal digits in division: 

Thus, bigDecimal.divide('2.00', '0.5') = 40.00000000
However, bigDecimal.divide('2.00', '0.50') = 4.00000000

Workaround: bigDecimal.divide( bigDecimal.round('2.00', 2), bigDecimal.round('0.5', 2)) = 4

npm

bigdecimal v.1.2.1
![image](https://user-images.githubusercontent.com/6086292/43864140-2a1ada42-9b5f-11e8-87b1-29d412d2b58c.png)

**Comment by gaoming13** [comment]
```js
let a = new bigDecimal('0.11005')
let b = new bigDecimal('0.1')
console.log(a.divide(b))

console.log(bigDecimal.divide('0.11005', '0.1'))

console.log(bigDecimal.divide(bigDecimal.round('0.11005', 16), bigDecimal.round('0.1', 16)))
```

```
bigDecimal { value: '11005.00000000' }
11005.00000000
1.10050000
```

**Comment by royNiladri** [comment]
@gaoming13 and @valerashylin 
Deployed patch for the reported issues. Sorry for the delay. Please use v1.2.2 and let know.
