### ISSUE TITLE
Comparison is returning true when it should be false

### ISSUE THREAD

**Issue by chasemc67** [royNiladri/js-big-decimal#21]
trying to do the following math: (94911150 / 94911151) == (94911151 / 94911152)

This should return false, but it appears to be returning true with this library. 

```
var bigDecimal = require('js-big-decimal');
var Decimal = require('decimal.js');

a = new Decimal(94911150);
b = new Decimal(94911151);
c = new Decimal(94911151);
d = new Decimal(94911152);


a1 = new bigDecimal(94911150);
b1 = new bigDecimal(94911151);
c1 = new bigDecimal(94911151);
d1 = new bigDecimal(94911152);


// (94911150 / 94911151) == (94911151 / 94911152)

console.log(a1.divide(b1).compareTo(c1.divide(d1)));

console.log(a.dividedBy(b).equals(c.dividedBy(d)));
```

```
0
false
```

it's my understanding that compareTo returning 0 means they're equal. If you check on wolfram alpha, that isn't the case

**Comment by royNiladri** [comment]
The default digits after decimal is 8, and in both the operations, it
results in the same 0.99999999. Please specify the number of digits to
consider (second parameter of divide) to get the expected answer.

**Comment by royNiladri** [comment]
@chasemc67 Closing the issue. Please check my previous comment.
