### ISSUE TITLE
How to calculate the remainder? I didn't find the divideandremainder () method

### ISSUE THREAD

**Issue by 1171736840** [royNiladri/js-big-decimal#32]
How to calculate the remainder? I didn't find the divideandremainder () method

**Comment by royNiladri** [comment]
It has not been implemented yet. Will take it up in the future. As a workaround (for now) you can do something like:
```
a - b*round(a/b)
```
Using the bigdecimal functions for.

**Comment by royNiladri** [comment]
@1171736840 The feature has been added to the new release. Please validate and let know.
