### ISSUE TITLE
divide error when i use 1e21 over number use

### ISSUE THREAD

**Issue by riverfrot** [royNiladri/js-big-decimal#37]
**Describe the bug**

An error occurs when dividing with a number greater than 1e21.

**To Reproduce**
Steps to reproduce the behavior, preferably with sample code.

const data = 1e21
multiplier = new bigDecimal(Math.pow(10, 18));
console.log(data / multiplier.value)
let divideAsset = bigDecimal.divide(received.toString(), multiplier.value, 18)
console.log('divideAsset')
console.log(divideAsset)
===>
10.000000000000000000(error)

**Expected behavior**
===>
1000.0000000000000000(Normal case)

**Additional context**

**Comment by royNiladri** [comment]
In the example code, i do not see you initialising receivedvalue. Moreover, you are not using it as expected.
Your data is not a string or bigdecimal.

**Comment by royNiladri** [comment]
Here is a working example:
```
var big = require("js-big-decimal")
a = new big('1e21');
b = new big('1e18')
console.log(a)
console.log(b)
console.log(a.divide(b))
```
![image](https://user-images.githubusercontent.com/16587916/99876491-09802980-2c1d-11eb-96bf-f9129885708c.png)
