### ISSUE TITLE
Wrong answer calculated

### ISSUE THREAD

**Issue by ChristopherDrum** [royNiladri/js-big-decimal#40]
**Describe the bug**
`bigDecimal.divide('123456789.123456','.0123456',18)`
returns `1000.006391940902021773`
but should return `10000063919.40902021773`

Decimal position is wrong.

**Additional context**
Using `npm` install in node; reports version `1.3.1`
Was working on an translation of `js-big-decimal` to Lua (for Pico8) and my code returned the incorrect answer.
Verified my answer against `js-big-decimal` and realized I had perfectly implemented it, down to even this bug. 🐛

**Comment by royNiladri** [comment]
Thanks for reporting.will look into it and get back within 48 hours.

**Comment by ChristopherDrum** [comment]
As I look further, here are more incorrect cases.

`bigDecimal.divide('2', '.0383292'))`
Expected: `52.17953935902653851371800089748`
Actual: `0.0000052179`

`bigDecimal.divide('.102', '.0383292',8))`
Expected: `2.66115650731035`
Actual:  `0.00000027`

So far, it seems to occur when the divisor has more decimal places than the dividend 🤔 
But there may be more cases I've yet to discover.

I've repaired these two particular cases in my own (Lua) code around the parsing of dividend decimal shift around decimal.ts, Line 29. But that doesn't fix the first case I reported. However, that seems related to similar decimal place parsing around Line 51-63, so it might be the same bug occuring at two different stages.

**Comment by royNiladri** [comment]
I am looking into it, but for now, I have found a workaround. If you add the leading zeros, like `0.102` or `0.123456`, it seems to work fine.
![image](https://user-images.githubusercontent.com/16587916/105662783-9930a580-5ef6-11eb-93e8-5e1ee68273c9.png)

**Comment by royNiladri** [comment]
Checkout the latest patch [v1.3.2](https://www.npmjs.com/package/js-big-decimal/v/1.3.2)

**Comment by ChristopherDrum** [comment]
Leading zero... ah, sorry, that just didn't cross my mind to try. Thanks for the repair, looks good 👍
