### ISSUE TITLE
A positive bug

### ISSUE THREAD

**Issue by informeronline** [royNiladri/js-big-decimal#43]
**Describe the bug**
Rounding up a negative number returns a positive value.

**To Reproduce**
Pick any number in this format: -x.996, -x.997, -x.998, -x.999 and rounding it HALF_UP gives a positive value.
Example:
new bigDecimal('-1.996').round(2, bigDecimal.RoundingModes.HALF_UP).getValue(); -> {value: "2.00"}
new bigDecimal('-2.997').round(2, bigDecimal.RoundingModes.HALF_UP).getValue(); -> {value: "3.00"}
etc..

**Expected behavior**
Rounding up a negative number returns a negative value.

**Additional context**
![image](https://user-images.githubusercontent.com/13853395/106872737-ecafaa00-66d3-11eb-8d29-d5fc27b41e32.png)

**Comment by royNiladri** [comment]
Thank you for reporting. The issue has been resolved in [v1.3.3](https://www.npmjs.com/package/js-big-decimal/v/1.3.3). Please update the package to the latest.
