### ISSUE TITLE
Rounding towards 0 from a negative number persists the "-" prefix

### ISSUE THREAD

**Issue by andrewsheffield** [royNiladri/js-big-decimal#64]
**Describe the bug**
When rounding to 0 from a negative number like "-0.0000005", the result will be something like "-0.00"

**To Reproduce**
new bigDecimal('-0.05').round(0)
=> '-0'

**Expected behavior**
any 0 value should not have a negative prefix

new bigDecimal('-0.05').round(0)
=> '0'

**Comment by royNiladri** [comment]
Fixed in v1.3.8. Please verify and close.

**Comment by andrewsheffield** [comment]
Right on! Thank you! Looks good.
