### ISSUE TITLE
stripTrailingZeros implement

### ISSUE THREAD

**Issue by royNiladri** [royNiladri/js-big-decimal#82]
### Discussed in https://github.com/royNiladri/js-big-decimal/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **uranik777** September 24, 2021</sup>
console.log( bigDecimal.add("0.0005000","1")); // 1.0005000
console.log( bigDecimal.add("0.0005000","1").stripTrailingZeros() ); // 1.0005
</div>

**Comment by yogski** [comment]
Hi, can I work on this?
I noticed that you already implement `trailZero()`, in `multiply.ts`.
My plan is as follows 
- separate it into independent function 
- importing it for existing functions
- adding basic test cases, plus usage in conjugation to other functions like `add()`, `multiply()`, `round()`

**Comment by royNiladri** [comment]
Hi! That would be great. Thank you so much 🙂

**Comment by royNiladri** [comment]
Consumed and released in v2.0.6
