### ISSUE TITLE
How about Math.abs

### ISSUE THREAD

**Issue by royNiladri** [royNiladri/js-big-decimal#83]
### Discussed in https://github.com/royNiladri/js-big-decimal/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **snowkidind** August  1, 2022</sup>
i want the absolute (unsigned) value of a bigD</div>

**Comment by EmmanJayDizon** [comment]
is this done?

**Comment by royNiladri** [comment]
Sadly not yet. Been busy with some other stuff. This is a relatively easy feature, so if you have bandwidth, please feel free to contribute! :)

**Comment by royNiladri** [comment]
This is now available in v1.3.15
