### ISSUE TITLE
add function doesn't work

### ISSUE THREAD

**Issue by steeveci** [royNiladri/js-big-decimal#85]
**Describe the bug**
n1.add(n2) where n1 and n2 are bigDecimal return error : 

Uncaught Error: Parameter is not a number: aN.NaNNaNNaN
    at __webpack_modules__.423.bigDecimal.validate

**Comment by royNiladri** [comment]
Please add exact case that is failing.

**Comment by steeveci** [comment]
ok I solved it.
`var n1 = new bigDecimal("2");
var n2 = new bigDecimal("2.5");
var cost = n1.add(n2);`

doesn't work because parameters are string but

`var n1 = new bigDecimal(Number("2"));
var n2 = new bigDecimal(Number("2.5"));
var cost = n1.add(n2);`

works

**Comment by royNiladri** [comment]
It should ideally work even without the cast to `Number`.
Here is an example using runkit:
![image](https://user-images.githubusercontent.com/16587916/198396916-bab36fbd-faf1-4f96-8b23-3e47fd9c732f.png)
